language: python
env:
  global:
  - secure: WxnAQRmA61mfHCw7wkzp+77ia2RKh111lZPm3kzeVlgARXWMWDlUp3jiTkFb5SagcTBh3TOVI+5/HUddjKLjRQJz4yvA3LkfoJ2PzBz7jGG6nvr16cknkJemD6kPZbqJC3AhGcgUKlbQXsQvu9dN6bQCDU5SolEFSNUY+QV/ozw=
  - secure: P5pPcavMSCel03a00r63dbO6lx/YFMxxLuGHXVpIvjPuN8WiXDyTI/0aKVGXORvSmvtyqRK07DSdzP/qyoUa2CtpVtbYEQDWJj2uXlufnE6L3rzR8R2oUt1v4zF8LHJ6gqzUKqi4YCg4KCzE6V6ANjsrJKKiiXCIdwfFYmRzpPU=
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.3
  - python: 3.4
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose jinja2 coverage cpp-coveralls pygments
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel -r requirements.txt --pre coveralls
install:
- python bootstrap-buildout.py
- CPPFLAGS=--coverage LDFLAGS=--coverage ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.ap import get_config; print(get_config())'
- ./bin/coverage run --source=bob.ap ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- cpp-coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*" --dump=cpp_cov.json
- coveralls --merge=cpp_cov.json
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
